name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test -- --coverage --reporter=cobertura
      - name: Cobertura coverage reporting
        uses: 5monkeys/cobertura-action@v1
        if: github.event_name == 'pull_request'
        with:
          report_file: ./coverage/cobertura-coverage.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 80